[tool.poetry]
name = "dec_profiler"
version = "0.1.0.2"
description = "Тестирование производительности кода"
authors = ["Denis Kustov <denis-kustov@rambler.ru>"]
license = "Apache-2.0"
readme = "dec_profiler/README.md"
homepage = "https://github.com/denisxab/dec_profiler"
repository = "https://github.com/denisxab/dec_profiler"
keywords = ["profiler"]
exclude = ["dec_profiler/.idea",
            "dec_profiler/venv",
            "dec_profiler/.git",
            "dec_profiler/.gitignore"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"